services:
  - type: web
    name: shopapp-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
